import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import JSZip from 'jszip';
import { newDocument, reveal, saveButton } from './helpers';

test('Page X of Y fields update in Print Layout, export and undo', async ({ page }) => {
	await page.goto('/?framework=vanilla');
	await newDocument(page);
	const editor = page.locator('docx-editor');
	const surface = editor.locator('.dve-paper > .ProseMirror');
	await surface.click();
	await page.keyboard.type('First page');
	await page.keyboard.press('Control+Enter');
	await page.keyboard.type('Second page');
	await editor.getByRole('tab', { name: 'Insert', exact: true }).click();
	const menu = editor.getByRole('combobox', { name: 'Page number', exact: true });
	await reveal(editor, menu);
	await menu.press('Alt+ArrowDown');
	const gallery = editor.getByRole('menu', { name: 'Page number', exact: true });
	const entry = gallery.locator('[data-value="bottom:center:pageOfTotal"]');
	await expect(entry.locator('svg text')).toHaveText('1 / 2');
	await entry.click();
	await expect(editor.locator('.dve-footer')).toHaveText(/Page 1 of 1/);
	const pending = page.waitForEvent('download');
	await saveButton(page).click();
	await (await pending).saveAs('test-results/page-number-total.docx');
	const zip = await JSZip.loadAsync(await readFile('test-results/page-number-total.docx'));
	const footer = await zip.file('word/footer1.xml')!.async('string');
	expect(footer).toMatch(/w:instr="\s*PAGE\s*"/);
	expect(footer).toMatch(/w:instr="\s*NUMPAGES\s*"/);
	await editor.getByRole('tab', { name: 'View', exact: true }).click();
	const layout = editor.getByRole('combobox', { name: 'Layout view', exact: true });
	await reveal(editor, layout);
	await layout.selectOption('print');
	const pages = editor.locator('.dve-print-page');
	await expect(pages).toHaveCount(2);
	await expect(pages.first()).toContainText('Page 1 of 2');
	await expect(pages.nth(1)).toContainText('Page 2 of 2');
	await layout.selectOption('draft');
	await editor.getByRole('tab', { name: 'Insert', exact: true }).click();
	await reveal(editor, menu);
	await menu.selectOption('bottom:right');
	await expect(editor.locator('.dve-footer [data-slot=default] p')).toHaveText('1');
	await surface.click();
	await page.keyboard.press('Control+z');
	await expect(editor.locator('.dve-footer')).toHaveText(/Page 1 of 1/);
});
