import { defineConfig } from 'tsup';
import { rawCss } from './tsup.config';

export default defineConfig({
	entry: {
		'dom/index': 'src/pptx/dom/index.ts',
		index: 'src/pptx/index.ts',
		'theme/index': 'src/pptx/theme/index.ts',
		'loader/index': 'src/pptx/loader/index.ts',
		'i18n/index': 'src/pptx/i18n/index.ts',
		'ai/index': 'src/pptx/ai/index.ts',
		'export/canvas-color-fix': 'src/pptx/export/canvas-color-fix.ts',
		'export/handout-layout': 'src/pptx/export/handout-layout.ts',
		'export/handout-master-chrome': 'src/pptx/export/handout-master-chrome.ts',
		'export/html-escape': 'src/pptx/export/html-escape.ts',
		'export/html2canvas-clone': 'src/pptx/export/html2canvas-clone.ts',
		'export/pdf-page-size': 'src/pptx/export/pdf-page-size.ts',
		'export/print-document': 'src/pptx/export/print-document.ts',
		'export/video-plan': 'src/pptx/export/video-plan.ts',
		'render/animation-authoring': 'src/pptx/render/animation-authoring.ts',
		'render/animation-preset-labels': 'src/pptx/render/animation-preset-labels.ts',
		'render/chart-combo-stock': 'src/pptx/render/chart-combo-stock.ts',
		'render/chart-overlays': 'src/pptx/render/chart-overlays.ts',
		'render/chart-surface-treemap': 'src/pptx/render/chart-surface-treemap.ts',
		'render/chart-view-model': 'src/pptx/render/chart-view-model.ts',
		'render/chart-waterfall-map': 'src/pptx/render/chart-waterfall-map.ts',
		'render/content-part-strokes': 'src/pptx/render/content-part-strokes.ts',
		'render/context-menu-target': 'src/pptx/render/context-menu-target.ts',
		'render/custom-fonts': 'src/pptx/render/custom-fonts.ts',
		'render/element-hit-test': 'src/pptx/render/element-hit-test.ts',
		'render/font-catalog': 'src/pptx/render/font-catalog.ts',
		'render/format-painter': 'src/pptx/render/format-painter.ts',
		'render/hyperlink-security': 'src/pptx/render/hyperlink-security.ts',
		'render/image-file-insertion': 'src/pptx/render/image-file-insertion.ts',
		'render/ink-rendering': 'src/pptx/render/ink-rendering.ts',
		'render/inspector-helpers': 'src/pptx/render/inspector-helpers.ts',
		'render/layout-gallery': 'src/pptx/render/layout-gallery.ts',
		'render/layout-preview': 'src/pptx/render/layout-preview.ts',
		'render/model3d-scene': 'src/pptx/render/model3d-scene.ts',
		'render/presentation-print-settings': 'src/pptx/render/presentation-print-settings.ts',
		'render/remap-text': 'src/pptx/render/remap-text.ts',
		'render/ribbon-animations-state': 'src/pptx/render/ribbon-animations-state.ts',
		'render/text-case-transform': 'src/pptx/render/text-case-transform.ts',
	},
	format: ['esm', 'cjs'],
	outExtension: ({ format }) => ({ js: format === 'esm' ? '.mjs' : '.cjs' }),
	esbuildPlugins: [rawCss],
	dts: false,
	splitting: true,
	sourcemap: false,
	clean: false,
	// Keep core and optional render/assistant runtimes external. Shared chunks
	// ensure public leaf entries reuse the same renderer state and registrations.
	outDir: 'dist/pptx',
	tsconfig: 'tsconfig.pptx.json',
	external: [
		/^ooxml-core(\/|$)/,
		'ooxml-ui/controls',
		'ooxml-ui/icons',
		'three',
		/^three\//u,
		'dompurify',
		'ai',
		'opentype.js',
	],
	treeshake: true,
	platform: 'neutral',
});
