import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import { editVsdx } from './edit';
import { parseVsdx } from './parser';

const directory = process.env.VISIO_NATIVE_RICH_FORMATTING_DIR;

/** Generated by scripts/record-visio-rich-formatting.ps1 using native Character/Paragraph edits. */
describe.skipIf(!directory)('native mixed-run formatting oracle', () => {
	it('matches native character and paragraph formatting at three drawing scales', async () => {
		const bytes = new Uint8Array(await readFile(join(directory!, 'original.vsdx')));
		const original = await parseVsdx(bytes);
		const native = await parseVsdx(new Uint8Array(await readFile(join(directory!, 'native.vsdx'))));
		const saved = await editVsdx(
			bytes,
			original.pages.map((page) => ({
				type: 'format-text',
				pageId: page.id,
				shapeId: '1',
				fontFamily: 'Calibri',
				fontSize: 18,
				fontColor: '#800080',
				bold: true,
				strikethrough: true,
				indentLeft: 18,
				horizontalAlign: 'justify',
				bullets: true,
			})),
		);
		const actual = await parseVsdx(saved.bytes);
		expect(actual.pages.map((page) => page.id)).toEqual(native.pages.map((page) => page.id));
		expect(actual.pages.map((page) => page.drawingToPageScale ?? 1)).toEqual([1, 0.5, 2]);
		for (const [index, page] of actual.pages.entries()) {
			const expected = native.pages[index]!;
			expect(page.shapes.map((shape) => shape.id)).toEqual(
				expected.shapes.map((shape) => shape.id),
			);
			for (const [shapeIndex, shape] of page.shapes.entries()) {
				const reference = expected.shapes[shapeIndex]!;
				expect(shape.text, `${page.name}/${shape.id}`).toEqual(reference.text);
				expect(shape.style).toEqual(reference.style);
				expect(shape.geometry).toEqual(reference.geometry);
				expect(shape.transform).toEqual(reference.transform);
			}
		}
		const before = await JSZip.loadAsync(bytes),
			after = await JSZip.loadAsync(saved.bytes);
		for (const [path, entry] of Object.entries(before.files)) {
			if (entry.dir || saved.changedParts.includes(path)) continue;
			expect(await after.file(path)!.async('uint8array'), path).toEqual(
				await entry.async('uint8array'),
			);
		}
		await writeFile(join(directory!, 'core.vsdx'), saved.bytes);
	});
});
