import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import { parseXml } from '../xml/index';
import { captureVisioClipboard } from './clipboard';
import { editVsdx, type VisioEdit } from './edit';
import { parseVsdx } from './parser';
import { children } from './sheet';
import { visioPasteCommand } from './ui/shape-clipboard';

const directory = process.env.VISIO_NATIVE_BATCH_DELETE_DIR;
/** Owned files generated by scripts/record-visio-batch-delete.ps1, without clipboard access. */
describe.skipIf(!directory)('native reference-closed Selection.Delete oracle', () => {
	it('matches surviving native shapes across nine cases and preserves retained XML/caches', async () => {
		const bytes = new Uint8Array(await readFile(join(directory!, 'original.vsdx')));
		const native = await parseVsdx(await readFile(join(directory!, 'native.vsdx')));
		const evidence = JSON.parse(
			(await readFile(join(directory!, 'evidence.json'), 'utf8')).trim(),
		) as {
			cases: { pageId: string; selection: string[]; control: string }[];
		};
		expect(evidence.cases).toHaveLength(9);
		const edits: VisioEdit[] = evidence.cases.flatMap((item) =>
			item.selection.map((shapeId) => ({ type: 'delete-shape', pageId: item.pageId, shapeId })),
		);
		const saved = await editVsdx(bytes, edits);
		const actual = await parseVsdx(saved.bytes);
		expect(actual.pages.map((page) => page.shapes)).toEqual(
			native.pages.map((page) => page.shapes),
		);
		const before = await JSZip.loadAsync(bytes),
			after = await JSZip.loadAsync(saved.bytes);
		for (const [path, entry] of Object.entries(before.files)) {
			if (entry.dir) continue;
			if (!saved.changedParts.includes(path)) {
				expect(await after.file(path)!.async('uint8array'), path).toEqual(
					await entry.async('uint8array'),
				);
				continue;
			}
			const originalRoot = parseXml(await entry.async('string')).documentElement;
			const savedRoot = parseXml(await after.file(path)!.async('string')).documentElement;
			expect(children(children(savedRoot, 'Shapes')[0], 'Shape')[0]!.toString(), path).toEqual(
				children(children(originalRoot, 'Shapes')[0], 'Shape')[2]!.toString(),
			);
		}
		await writeFile(join(directory!, 'core.vsdx'), saved.bytes);
	});
	it('can capture, remove and restore native closed selections entirely through core', async () => {
		const bytes = new Uint8Array(await readFile(join(directory!, 'original.vsdx')));
		const evidence = JSON.parse(
			(await readFile(join(directory!, 'evidence.json'), 'utf8')).trim(),
		) as { cases: { pageId: string; selection: string[] }[] };
		const captures = await Promise.all(
			evidence.cases.map((item) => captureVisioClipboard(bytes, item.pageId, item.selection)),
		);
		const deleted = await editVsdx(
			bytes,
			evidence.cases.flatMap((item) =>
				item.selection.map((shapeId) => ({ type: 'delete-shape', pageId: item.pageId, shapeId })),
			),
		);
		const source = await parseVsdx(bytes),
			target = await parseVsdx(deleted.bytes);
		const edits = captures.map((clipboard, index) =>
			visioPasteCommand(target.pages[index]!, clipboard, { x: 0, y: 0 })!,
		);
		const saved = await editVsdx(deleted.bytes, edits);
		const restored = await parseVsdx(saved.bytes);
		for (const [index, page] of restored.pages.entries())
			for (const [position, original] of source.pages[index]!.shapes.entries()) {
				const actual = page.shapes[position === 2 ? 0 : position + 1]!;
				expect(actual.text).toEqual(original.text);
				expect(actual.geometry).toEqual(original.geometry);
				expect(actual.transform).toEqual(original.transform);
			}
		await writeFile(join(directory!, 'cut-paste-core.vsdx'), saved.bytes);
	});
});
