import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import { editVsdx, type VisioEdit } from './edit';
import { parseVsdx } from './parser';

const directory = process.env.VISIO_NATIVE_FORMATTING_DIR;

/** Generated by scripts/record-visio-formatting.ps1 in a separate owned Visio instance. */
describe.skipIf(!directory)('native Visio formatting, page scale and stacking oracle', () => {
	it('matches saved native formatting and order while preserving every unrelated ZIP payload', async () => {
		const original = new Uint8Array(await readFile(join(directory!, 'original.vsdx')));
		const source = await parseVsdx(original);
		const evidence = JSON.parse(await readFile(join(directory!, 'evidence.json'), 'utf8')) as {
			order?: 'front' | 'back' | 'forward' | 'backward';
			extended?: boolean;
		};
		const reference = await parseVsdx(
			new Uint8Array(await readFile(join(directory!, 'native.vsdx'))),
		);
		const edits: VisioEdit[] = source.pages.flatMap((page) => [
			{
				type: 'format-text',
				pageId: page.id,
				shapeId: '1',
				fontFamily: 'Calibri',
				fontSize: 18,
				bold: true,
				italic: true,
				underline: true,
				horizontalAlign: 'right',
				verticalAlign: 'top',
				...(evidence.extended
					? {
							fontColor: '#800080',
							strikethrough: true,
							bullets: true,
							indentLeft: 18,
							horizontalAlign: 'justify' as const,
						}
					: {}),
			},
			{
				type: 'format-shape',
				pageId: page.id,
				shapeId: '1',
				fillColor: '#ff0000',
				lineColor: '#0000ff',
				lineWeight: 2.25,
			},
			{ type: 'reorder-shape', pageId: page.id, shapeId: '1', order: evidence.order ?? 'front' },
		]);
		const saved = await editVsdx(original, edits);
		const actual = await parseVsdx(saved.bytes);
		expect(source.pages.map((page) => page.drawingToPageScale ?? 1)).toEqual([1, 0.5, 2]);
		for (const [index, page] of actual.pages.entries()) {
			const expected = reference.pages[index]!;
			expect(page.shapes.map((shape) => shape.id)).toEqual(
				expected.shapes.map((shape) => shape.id),
			);
			const shape = page.shapes.find((candidate) => candidate.id === '1')!;
			const native = expected.shapes.find((candidate) => candidate.id === '1')!;
			expect(shape.text).toEqual(native.text);
			expect(shape.style).toEqual(native.style);
			expect(shape.geometry).toEqual(native.geometry);
			expect(shape.transform).toEqual(native.transform);
		}
		const before = await JSZip.loadAsync(original),
			after = await JSZip.loadAsync(saved.bytes);
		for (const path of Object.keys(before.files)) {
			if (before.files[path]!.dir || saved.changedParts.includes(path)) continue;
			expect(await after.file(path)!.async('uint8array'), path).toEqual(
				await before.file(path)!.async('uint8array'),
			);
		}
		await writeFile(join(directory!, 'core.vsdx'), saved.bytes);
		// Repeating all formatting and an already-extreme stack position preserves exact bytes.
		if (!evidence.order || evidence.order === 'front' || evidence.order === 'back')
			expect((await editVsdx(saved.bytes, edits)).bytes).toEqual(saved.bytes);
	});
});
