import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import { parseXml } from '../xml/index';
import { editVsdx, type VisioEdit } from './edit';
import { parseVsdx } from './parser';
import { attribute, children } from './sheet';
import { visioDuplicateCommand } from './ui/shape-duplicate';

const directory = process.env.VISIO_NATIVE_DUPLICATE_DIR;

/** Generated by scripts/record-visio-duplicate.ps1 with native Selection.Duplicate. */
describe.skipIf(!directory)('native Visio duplicate oracle', () => {
	it('matches IDs, names, rich text, geometry and caches across three drawing scales', async () => {
		const bytes = new Uint8Array(await readFile(join(directory!, 'original.vsdx')));
		const nativeBytes = new Uint8Array(await readFile(join(directory!, 'native.vsdx')));
		const source = await parseVsdx(bytes);
		const native = await parseVsdx(nativeBytes);
		const evidence = JSON.parse(await readFile(join(directory!, 'evidence.json'), 'utf8')) as {
			cases: { pageId: string; selection: string[] }[];
		};
		const edits: VisioEdit[] = evidence.cases.map((item) => {
			const page = source.pages.find((candidate) => candidate.id === item.pageId)!;
			const edit = visioDuplicateCommand(page, item.selection);
			expect(edit, page.name).toBeDefined();
			return edit!;
		});
		const saved = await editVsdx(bytes, edits);
		const actual = await parseVsdx(saved.bytes);
		expect(actual.pages.map((page) => page.id)).toEqual(native.pages.map((page) => page.id));
		for (const [pageIndex, page] of actual.pages.entries()) {
			const expected = native.pages[pageIndex]!;
			expect(
				page.shapes.map((shape) => shape.id),
				page.name,
			).toEqual(expected.shapes.map((shape) => shape.id));
			for (const [index, shape] of page.shapes.entries()) {
				const reference = expected.shapes[index]!;
				expect(shape.text, `${page.name}/${shape.id}`).toEqual(reference.text);
				expect(shape.style).toEqual(reference.style);
				expect(shape.geometry).toEqual(reference.geometry);
				shape.transform.forEach((value, index) =>
					expect(value).toBeCloseTo(reference.transform[index]!, 12),
				);
			}
		}
		const before = await JSZip.loadAsync(bytes);
		const after = await JSZip.loadAsync(saved.bytes);
		const reference = await JSZip.loadAsync(nativeBytes);
		for (const [path, entry] of Object.entries(before.files)) {
			if (entry.dir) continue;
			if (!saved.changedParts.includes(path)) {
				expect(await after.file(path)!.async('uint8array'), path).toEqual(
					await entry.async('uint8array'),
				);
				continue;
			}
			const root = parseXml(await after.file(path)!.async('string')).documentElement;
			const nativeRoot = parseXml(await reference.file(path)!.async('string')).documentElement;
			const shapes = children(children(root, 'Shapes')[0], 'Shape');
			const nativeShapes = children(children(nativeRoot, 'Shapes')[0], 'Shape');
			for (const [index, shape] of shapes.entries()) {
				const expected = nativeShapes[index]!;
				expect(attribute(shape, 'NameU')).toEqual(attribute(expected, 'NameU'));
				expect(attribute(shape, 'UniqueID')).toEqual(attribute(expected, 'UniqueID'));
				const user = children(shape, 'Section').find((node) => attribute(node, 'N') === 'User');
				const nativeUser = children(expected, 'Section').find(
					(node) => attribute(node, 'N') === 'User',
				);
				for (const row of children(user, 'Row')) {
					const nativeRow = children(nativeUser, 'Row').find(
						(node) => attribute(node, 'N') === attribute(row, 'N'),
					)!;
					const value = children(row, 'Cell').find((node) => attribute(node, 'N') === 'Value')!;
					const nativeValue = children(nativeRow, 'Cell').find(
						(node) => attribute(node, 'N') === 'Value',
					)!;
					expect(Number(attribute(value, 'V'))).toBeCloseTo(
						Number(attribute(nativeValue, 'V')),
						12,
					);
				}
			}
		}
		await writeFile(join(directory!, 'core.vsdx'), saved.bytes);
	});
});
