// Stamp the binding version; the renderer is imported from ooxml-ui/pptx.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// Also stamp this package's own `package.json` version into a tiny generated
// module (`internal/version.ts`), so File > Account's About panel can show a
// real version without ng-packagr trying to compile source from outside
// `src/` (importing `../package.json` directly would sit outside `rootDir`).
const pkgPath = resolve(here, '../package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const versionFile = resolve(here, '../src/internal/version.ts');
writeFileSync(
	versionFile,
	`// Generated by scripts/inline-shared.mjs from package.json. Do not edit.\nexport const PPTX_ANGULAR_VIEWER_VERSION = ${JSON.stringify(pkg.version)};\n`,
);

console.log(`[inline-shared] wrote ${versionFile} (v${pkg.version})`);
