/**
 * The ooxml-ui design tokens: the single source of every colour, size, space, radius, type,
 * shadow, motion and layering value the controls use. Controls never write a literal; they read
 * `tok('--office-…')`, which expands to `var(--office-…, <default>)`, so a control renders
 * correctly with or without the installed theme and a host overrides any token on `:root` or on
 * any container. `THEME_CSS` (theme.ts) declares these defaults on `:root` plus dark and
 * forced-colours values. Component tokens default to the semantic ones.
 */
export const OFFICE_TOKENS = {
	// Colour: semantic
	'--office-foreground': '#1f2937',
	'--office-muted-foreground': '#6b7280',
	'--office-background': '#ffffff',
	'--office-surface': '#f3f4f6',
	'--office-selected': '#e5e7eb',
	'--office-border': '#d1d5db',
	'--office-accent': '#2563eb',
	'--office-accent-foreground': '#ffffff',
	'--office-ring': '#2563eb',
	'--office-danger': '#b91c1c',
	'--office-danger-foreground': '#ffffff',
	'--office-warning': '#d97706',
	'--office-warning-foreground': '#ffffff',
	'--office-info': '#3b82f6',
	'--office-popover': 'var(--office-background, #ffffff)',
	'--office-popover-foreground': 'var(--office-foreground, #1f2937)',
	'--office-overlay': 'rgb(0 0 0 / 40%)',
	'--office-notice-background': '#fef3c7',
	'--office-notice-foreground': '#78350f',
	'--office-notice-border': 'rgb(180 83 9 / 30%)',
	'--office-notice-accent': '#d97706',
	'--office-keytip-background': '#ffffff',
	'--office-keytip-foreground': '#1f1f1f',
	'--office-keytip-border': '#8a8886',
	'--office-highlight': '#dc2626',
	'--office-paper': '#ffffff',
	'--office-accent-hover': 'color-mix(in srgb, var(--office-accent, #2563eb) 85%, #000)',
	// Typography
	'--office-font': 'system-ui, -apple-system, "Segoe UI", sans-serif',
	'--office-font-size-3xs': '9px',
	'--office-font-size-2xs': '10px',
	'--office-font-size-xs': '11px',
	'--office-font-size-sm': '12px',
	'--office-font-size': '13px',
	'--office-font-size-md': '14px',
	'--office-font-size-lg': '15px',
	'--office-font-size-xl': '18px',
	'--office-font-weight-medium': '500',
	'--office-font-weight-bold': '600',
	'--office-line-height': '1.4',
	'--office-line-height-tight': '1.2',
	'--office-icon-stroke': '1.5',
	// Space
	'--office-space-px': '1px',
	'--office-space-0': '2px',
	'--office-space-1': '4px',
	'--office-space-1-5': '6px',
	'--office-space-2': '8px',
	'--office-space-2-5': '10px',
	'--office-space-3': '12px',
	'--office-space-3-5': '14px',
	'--office-space-4': '16px',
	'--office-space-5': '20px',
	'--office-space-6': '24px',
	// Shape
	'--office-border-width': '1px',
	'--office-border-width-thick': '2px',
	'--office-radius-xs': '2px',
	'--office-radius-sm': '3px',
	'--office-radius': '4px',
	'--office-radius-md': '6px',
	'--office-radius-lg': '8px',
	'--office-radius-full': '999px',
	// Focus
	'--office-focus-width': '2px',
	'--office-focus-offset': '2px',
	// Sizes
	'--office-target-size': '28px',
	'--office-target-size-touch': '44px',
	'--office-control-height': '24px',
	'--office-control-height-md': '28px',
	'--office-control-height-lg': '32px',
	'--office-input-height': '26px',
	'--office-control-height-xs': '22px',
	'--office-icon-size-xs': '10px',
	'--office-icon-size-sm': '12px',
	'--office-icon-size': '14px',
	'--office-icon-size-md': '16px',
	'--office-icon-size-ml': '18px',
	'--office-icon-size-lg': '20px',
	// Elevation and layering
	'--office-shadow-sm': '0 1px 3px rgb(0 0 0 / 20%)',
	'--office-shadow': '0 6px 20px rgb(0 0 0 / 18%)',
	'--office-shadow-lg': '0 10px 25px rgb(0 0 0 / 20%)',
	'--office-z-popover': '1100',
	'--office-z-dialog': '1000',
	'--office-z-backstage': '30',
	// Motion
	'--office-duration-fast': '.12s',
	'--office-duration': '.15s',
	'--office-duration-spin': '.8s',
	// Component: fields
	'--office-field-height': '28px',
	'--office-field-height-lg': '40px',
	'--office-field-radius': '5px',
	'--office-field-border': 'var(--office-border, #d1d5db)',
	'--office-field-border-focus': 'var(--office-ring, #2563eb)',
	'--office-field-background': 'var(--office-background, #ffffff)',
	'--office-field-foreground': 'var(--office-foreground, #1f2937)',
	'--office-field-placeholder': 'var(--office-muted-foreground, #6b7280)',
	// Component: checkbox, radio, switch
	'--office-checkbox-size': '16px',
	'--office-checkbox-size-touch': '22px',
	'--office-checkbox-radius': '3px',
	'--office-checkbox-border': 'var(--office-border, #d1d5db)',
	'--office-checkbox-background': 'var(--office-background, #ffffff)',
	'--office-checkbox-accent': 'var(--office-accent, #2563eb)',
	'--office-checkbox-accent-foreground': 'var(--office-accent-foreground, #ffffff)',
	'--office-radio-dot-size': '8px',
	'--office-radio-dot-size-touch': '12px',
	'--office-switch-width': '32px',
	'--office-switch-height': '18px',
	'--office-switch-width-touch': '44px',
	'--office-switch-height-touch': '24px',
	'--office-switch-border-width': '1px',
	'--office-switch-knob-size': '12px',
	'--office-switch-knob-size-touch': '18px',
	'--office-switch-knob-offset': '2px',
	'--office-switch-border': 'var(--office-border, #d1d5db)',
	'--office-switch-track': 'var(--office-surface, #f3f4f6)',
	'--office-switch-track-on': 'var(--office-accent, #2563eb)',
	'--office-switch-thumb': 'var(--office-foreground, #1f2937)',
	'--office-switch-thumb-on': 'var(--office-accent-foreground, #ffffff)',
	// Component: ribbon, status bar, tabs
	'--office-ribbon-tab-height': '35px',
	'--office-ribbon-group-gap': '2px',
	'--office-ribbon-group-height': '78px',
	'--office-ribbon-group-padding': '4px 8px 2px',
	'--office-ribbon-separator-inset': '0px',
	'--office-ribbon-separator': 'color-mix(in srgb, var(--office-border, #d1d5db) 60%, transparent)',
	'--office-ribbon-caption-size': '10px',
	'--office-ribbon-caption-padding': '2px 0 0',
	'--office-launcher-inset-end': '-6px',
	'--office-launcher-inset-bottom': '-1px',
	'--office-ribbon-compact-row-max': '36px',
	'--office-ribbon-stack-max-height': '80px',
	'--office-ribbon-collapse-x': '8px',
	'--office-ribbon-collapse-y': '120px',
	'--office-command-icon-color': 'currentColor',
	'--office-command-large-height': '66px',
	'--office-command-large-min-width': '48px',
	'--office-command-large-max-width': '80px',
	'--office-command-large-icon': '32px',
	'--office-command-small-icon': '16px',
	'--office-command-tall-height': '62px',
	'--office-command-tall-min-width': '40px',
	'--office-command-tall-icon': '30px',
	'--office-command-active': 'color-mix(in srgb, var(--office-accent, #2563eb) 15%, transparent)',
	'--office-collapsed-group-min-width': '56px',
	'--office-ribbon-caption-line-height': '12px',
	'--office-ribbon-row-height': '22px',
	'--office-ribbon-file-min-width': '52px',
	'--office-launcher-width': '16px',
	'--office-launcher-height': '14px',
	'--office-tab-indicator-width': '2.5px',
	'--office-status-bar-height': '24px',
	'--office-tab-height': '28px',
	'--office-tab-max-width': '220px',
	'--office-zoom-slider-width': '120px',
	'--office-zoom-slider-min-width': '48px',
	'--office-zoom-value-width': '40px',
	// Component: panels and dialogs
	'--office-dialog-width': 'auto',
	'--office-dialog-max-width': 'min(640px, 100vw)',
	'--office-dialog-max-height': '90vh',
	'--office-dialog-min-width': 'min(320px, 100vw)',
	'--office-dialog-button-min-width': '76px',
	'--office-options-width': 'min(820px, 100vw)',
	'--office-options-nav-width': '180px',
	'--office-options-min-height': 'min(440px, 70vh)',
	'--office-options-label-width': '180px',
	'--office-options-row-height': '30px',
	'--office-options-number-width': '80px',
	'--office-info-size': '15px',
	'--office-selection-bar-width': '3px',
	'--office-backstage-nav-width': '200px',
	'--office-backstage-nav-background': 'var(--office-accent, #2563eb)',
	'--office-backstage-nav-foreground': 'var(--office-accent-foreground, #ffffff)',
	'--office-backstage-item-hover': 'rgb(0 0 0 / 22%)',
	'--office-backstage-padding': '28px 40px',
	'--office-backstage-back-size': '36px',
	'--office-backstage-item-height': '38px',
	'--office-menu-min-width': '180px',
	'--office-menu-max-height': '60vh',
	'--office-context-menu-min-width': '200px',
	'--office-search-popup-min-width': '240px',
	'--office-search-popup-max-height': '320px',
	'--office-select-max-height': '240px',
	'--office-select-background': 'var(--office-background, #ffffff)',
	'--office-select-menu-min-width': '90px',
	'--office-select-option-active':
		'color-mix(in srgb, var(--office-accent, #2563eb) 20%, var(--office-popover, #ffffff))',
	'--office-select-ribbon-menu-width': '192px',
	'--office-font-picker-max-height': '320px',
	'--office-font-picker-width': '256px',
	'--office-chevron-size': '6px',
	'--office-ribbon-combo-height': '28px',
	'--office-ribbon-icon-select-width': '36px',
	'--office-search-width': '320px',
	'--office-print-preview-width': '420px',
	'--office-find-max-width': '640px',
	'--office-find-bar-height': '40px',
	'--office-ruler-size': '18px',
	'--office-avatar-size': '48px',
	'--office-avatar-color': 'var(--office-muted-foreground, #6b7280)',
	'--office-toast-width': '360px',
	'--office-account-field-width': '320px',
	// Component: title bar
	'--office-title-bar-height': '36px',
	'--office-title-bar-below-height': '28px',
	'--office-title-bar-background': 'var(--office-surface, #f3f4f6)',
	'--office-title-bar-foreground': 'var(--office-foreground, #1f2937)',
	'--office-title-bar-border': 'var(--office-border, #d1d5db)',
	'--office-title-bar-mark-size': '20px',
	'--office-title-bar-mark-background': 'var(--office-accent, #2563eb)',
	'--office-title-bar-mark-foreground': 'var(--office-accent-foreground, #ffffff)',
	'--office-title-bar-name-max-width': '240px',
	'--office-title-bar-name-max-width-narrow': '140px',
	'--office-title-bar-search-max-width': '448px',
	'--office-title-bar-results-max-height': '256px',
} as const;

export type OfficeToken = keyof typeof OFFICE_TOKENS;

/** `var(--office-…, <default>)` for a declared token. The default comes from the table. */
export function tok(name: OfficeToken): string {
	return `var(${name}, ${OFFICE_TOKENS[name]})`;
}

/** The standard keyboard focus ring. */
export const FOCUS_RING = `outline: ${tok('--office-focus-width')} solid ${tok('--office-ring')}; outline-offset: ${tok('--office-focus-offset')};`;

/**
 * Layout breakpoints. CSS forbids custom properties in media queries, so these are the only
 * lengths written literally; every control uses these two.
 */
export const COMPACT = '(max-width: 767px)';
export const TOUCH = `(pointer: coarse), ${COMPACT}`;
