/** Strings for picture, link, character style and hidden-text commands. */
export const commandStrings = {
	en: {
		'Character style': 'Character style',
		'No character style': 'No character style',
		Illustrations: 'Illustrations',
		'Insert picture': 'Insert picture',
		Pictures: 'Pictures',
		Links: 'Links',
		'Insert link': 'Insert link',
		Link: 'Link',
		'Text to display': 'Text to display',
		Address: 'Address',
		'Place in this document': 'Place in this document',
		ScreenTip: 'ScreenTip',
		'Remove link': 'Remove link',
		Cancel: 'Cancel',
		Insert: 'Insert',
		Show: 'Show',
		'Show hidden text': 'Show hidden text',
		'Hidden text': 'Hidden text',
		'Format picture': 'Format picture',
		Format: 'Format',
		'Alt text': 'Alt text',
		Width: 'Width',
		Height: 'Height',
		'Lock aspect ratio': 'Lock aspect ratio',
		OK: 'OK',
	},
	fr: {
		'Character style': 'Style de caractère',
		'No character style': 'Aucun style de caractère',
		Illustrations: 'Illustrations',
		'Insert picture': 'Insérer une image',
		Pictures: 'Images',
		Links: 'Liens',
		'Insert link': 'Insérer un lien',
		Link: 'Lien',
		'Text to display': 'Texte à afficher',
		Address: 'Adresse',
		'Place in this document': 'Emplacement dans ce document',
		ScreenTip: 'Info-bulle',
		'Remove link': 'Supprimer le lien',
		Cancel: 'Annuler',
		Insert: 'Insérer',
		Show: 'Afficher',
		'Show hidden text': 'Afficher le texte masqué',
		'Hidden text': 'Texte masqué',
		'Format picture': 'Format de l’image',
		Format: 'Format',
		'Alt text': 'Texte de remplacement',
		Width: 'Largeur',
		Height: 'Hauteur',
		'Lock aspect ratio': 'Conserver les proportions',
		OK: 'OK',
	},
} as const;
