/** Strings for picture, link, character style and hidden-text commands. */
export const commandStrings = {
	en: {
		'Character style': 'Character style',
		'No character style': 'No character style',
		Illustrations: 'Illustrations',
		'Insert picture': 'Insert picture',
		Pictures: 'Pictures',
		Links: 'Links',
		'Insert link': 'Insert link',
		Link: 'Link',
		'Text to display': 'Text to display',
		Address: 'Address',
		'Place in this document': 'Place in this document',
		ScreenTip: 'ScreenTip',
		'Remove link': 'Remove link',
		Cancel: 'Cancel',
		Insert: 'Insert',
		Show: 'Show',
		'Show hidden text': 'Show hidden text',
		'Hidden text': 'Hidden text',
		'Format picture': 'Format picture',
		Format: 'Format',
		'Alt text': 'Alt text',
		Width: 'Width',
		Height: 'Height',
		'Lock aspect ratio': 'Lock aspect ratio',
		OK: 'OK',
		Footnotes: 'Footnotes',
		References: 'References',
		'Table of Contents': 'Table of Contents',
		'Insert table of contents': 'Insert table of contents',
		'Update table of contents': 'Update table of contents',
		'Update Table': 'Update Table',
		'This document has no table of contents to update.':
			'This document has no table of contents to update.',
		'Insert footnote': 'Insert footnote',
		'Insert endnote': 'Insert endnote',
		Footnote: 'Footnote',
		Endnote: 'Endnote',
		Columns: 'Columns',
		'One column': 'One column',
		'Two columns': 'Two columns',
		'Three columns': 'Three columns',
		'Section breaks': 'Section breaks',
		'Next page section break': 'Next page section break',
		'Continuous section break': 'Continuous section break',
		'Next page': 'Next page',
		Continuous: 'Continuous',
		'Page numbers': 'Page numbers',
		'Page number format': 'Page number format',
		'Page numbering': 'Page numbering',
		'Continue from previous section': 'Continue from previous section',
		'Start at 1': 'Start at 1',
		'Different first page': 'Different first page',
		'Different odd and even pages': 'Different odd and even pages',
		'Different odd & even pages': 'Different odd & even pages',
		'Vertical alignment': 'Vertical alignment',
		Top: 'Top',
		Center: 'Center',
		Justified: 'Justified',
		Bottom: 'Bottom',
		'Even page section break': 'Even page section break',
		'Odd page section break': 'Odd page section break',
		'Even page': 'Even page',
		'Odd page': 'Odd page',
	},
	fr: {
		'Character style': 'Style de caractère',
		'No character style': 'Aucun style de caractère',
		Illustrations: 'Illustrations',
		'Insert picture': 'Insérer une image',
		Pictures: 'Images',
		Links: 'Liens',
		'Insert link': 'Insérer un lien',
		Link: 'Lien',
		'Text to display': 'Texte à afficher',
		Address: 'Adresse',
		'Place in this document': 'Emplacement dans ce document',
		ScreenTip: 'Info-bulle',
		'Remove link': 'Supprimer le lien',
		Cancel: 'Annuler',
		Insert: 'Insérer',
		Show: 'Afficher',
		'Show hidden text': 'Afficher le texte masqué',
		'Hidden text': 'Texte masqué',
		'Format picture': 'Format de l’image',
		Format: 'Format',
		'Alt text': 'Texte de remplacement',
		Width: 'Largeur',
		Height: 'Hauteur',
		'Lock aspect ratio': 'Conserver les proportions',
		OK: 'OK',
		References: 'Références',
		'Table of Contents': 'Table des matières',
		'Insert table of contents': 'Insérer une table des matières',
		'Update table of contents': 'Mettre à jour la table des matières',
		'Update Table': 'Mettre à jour la table',
		'This document has no table of contents to update.':
			'Ce document ne contient aucune table des matières à mettre à jour.',
		'Insert footnote': 'Insérer une note de bas de page',
		'Insert endnote': 'Insérer une note de fin',
		Footnote: 'Note de bas de page',
		Endnote: 'Note de fin',
		Columns: 'Colonnes',
		'One column': 'Une colonne',
		'Two columns': 'Deux colonnes',
		'Three columns': 'Trois colonnes',
		'Section breaks': 'Sauts de section',
		'Next page section break': 'Saut de section (page suivante)',
		'Continuous section break': 'Saut de section (continu)',
		'Next page': 'Page suivante',
		Continuous: 'Continu',
		'Page numbers': 'Numéros de page',
		'Page number format': 'Format des numéros de page',
		'Page numbering': 'Numérotation des pages',
		'Continue from previous section': 'À la suite de la section précédente',
		'Start at 1': 'Commencer à 1',
		'Different first page': 'Première page différente',
		'Different odd and even pages': 'Pages paires et impaires différentes',
		'Different odd & even pages': 'Paires et impaires différentes',
		'Vertical alignment': 'Alignement vertical',
		Top: 'Haut',
		Center: 'Centré',
		Justified: 'Justifié',
		Bottom: 'Bas',
		'Even page section break': 'Saut de section (page paire)',
		'Odd page section break': 'Saut de section (page impaire)',
		'Even page': 'Page paire',
		'Odd page': 'Page impaire',
	},
} as const;
