/** Strings for the Word-style window chrome: title bar, File backstage and status bar. */
export const chromeStrings = {
	en: {
		File: 'File',
		Alignment: 'Alignment',
		'Quick access': 'Quick access',
		Save: 'Save',
		'Tell me what you want to do': 'Tell me what you want to do',
		'Editing mode': 'Editing mode',
		Editing: 'Editing',
		Viewing: 'Viewing',
		'Show comments': 'Show comments',
		'Unsaved changes': 'Unsaved changes',
		Saved: 'Saved',
		'Saving…': 'Saving…',
		'Saved to this PC': 'Saved to this PC',
		'Back to document': 'Back to document',
		Info: 'Info',
		New: 'New',
		Open: 'Open',
		'Save a copy as DOCX': 'Save a copy as DOCX',
		'Blank document': 'Blank document',
		'Browse…': 'Browse…',
		'Open a Word document (.docx or .doc) from this device.':
			'Open a Word document (.docx or .doc) from this device.',
		'Files are processed entirely in the browser.': 'Files are processed entirely in the browser.',
		'Document properties': 'Document properties',
		'File name': 'File name',
		Words: 'Words',
		Paragraphs: 'Paragraphs',
		Tables: 'Tables',
		'Compatibility notes': 'Compatibility notes',
		'No compatibility notes for this document.': 'No compatibility notes for this document.',
		'status.note': '{count} compatibility note',
		'status.notes': '{count} compatibility notes',
		'Web Layout': 'Web Layout',
		'Zoom out': 'Zoom out',
		'Zoom in': 'Zoom in',
		'Zoom level': 'Zoom level',
		'Reset zoom': 'Reset zoom',
		'No matching commands': 'No matching commands',
		'Discard unsaved changes and start a new document?':
			'Discard unsaved changes and start a new document?',
	},
	fr: {
		File: 'Fichier',
		Alignment: 'Alignement',
		'Quick access': 'Accès rapide',
		Save: 'Enregistrer',
		'Tell me what you want to do': 'Dites-nous ce que vous voulez faire',
		'Editing mode': 'Mode d’édition',
		Editing: 'Modification',
		Viewing: 'Lecture',
		'Show comments': 'Afficher les commentaires',
		'Unsaved changes': 'Modifications non enregistrées',
		Saved: 'Enregistré',
		'Saving…': 'Enregistrement…',
		'Saved to this PC': 'Enregistré sur ce PC',
		'Back to document': 'Retour au document',
		Info: 'Informations',
		New: 'Nouveau',
		Open: 'Ouvrir',
		'Save a copy as DOCX': 'Enregistrer une copie en DOCX',
		'Blank document': 'Document vierge',
		'Browse…': 'Parcourir…',
		'Open a Word document (.docx or .doc) from this device.':
			'Ouvrez un document Word (.docx ou .doc) depuis cet appareil.',
		'Files are processed entirely in the browser.':
			'Les fichiers sont traités entièrement dans le navigateur.',
		'Document properties': 'Propriétés du document',
		'File name': 'Nom du fichier',
		Words: 'Mots',
		Paragraphs: 'Paragraphes',
		Tables: 'Tableaux',
		'Compatibility notes': 'Notes de compatibilité',
		'No compatibility notes for this document.': 'Aucune note de compatibilité pour ce document.',
		'status.note': '{count} note de compatibilité',
		'status.notes': '{count} notes de compatibilité',
		'Web Layout': 'Web',
		'Zoom out': 'Zoom arrière',
		'Zoom in': 'Zoom avant',
		'Zoom level': 'Niveau de zoom',
		'Reset zoom': 'Réinitialiser le zoom',
		'No matching commands': 'Aucune commande correspondante',
		'Discard unsaved changes and start a new document?':
			'Abandonner les modifications non enregistrées et créer un document ?',
	},
} as const;
