import type { LegacyRibbonLabel } from './ribbon-legacy-labels';

/**
 * Stable, locale-independent ids of every ribbon control. `hiddenActions` is keyed on these ids;
 * the English labels below are only the keys the localizer uses to find a control's display text.
 * `element-api.test.ts` fails when a control is added to or removed from the ribbon without
 * updating this list.
 */
export const RIBBON_ACTION_IDS = [
	'paste',
	'insert-caption',
	'cross-reference',
	'ruler',
	'page-setup-dialog',
	'cover-page',
	'bookmark',
	'sort',
	'find-options',
	'select-options',
	'add-text',
	'blank-page',
	'read-aloud',
	'gridlines',
	'shading',
	'borders',
	'header',
	'footer',
	'page-number',
	'page-size',
	'font-dialog',
	'paragraph-dialog',
	'indent-left',
	'indent-right',
	'zoom-actual-size',
	'page-width',
	'one-page',
	'word-count',
	'spelling',
	'symbol',
	'date-and-time',
	'change-case',
	'format-painter',
	'show-paragraph-marks',
	'select-all',
	'replace',
	'cut',
	'copy',
	'grow-font',
	'shrink-font',
	'font-family',
	'font-size',
	'bold',
	'italic',
	'underline',
	'strikethrough',
	'superscript',
	'subscript',
	'font-color',
	'text-highlight',
	'clear-formatting',
	'decrease-indent',
	'increase-indent',
	'spacing-after',
	'spacing-before',
	'line-spacing',
	'bulleted-list',
	'numbered-list',
	'decrease-list-level',
	'increase-list-level',
	'remove-list',
	'align-left',
	'align-center',
	'align-right',
	'justify',
	'find-and-replace',
	'insert-table',
	'insert-picture',
	'format-picture',
	'insert-link',
	'insert-page-break',
	'insert-column-break',
	'margins',
	'orientation',
	'vertical-alignment',
	'columns',
	'page-number-format',
	'page-numbering',
	'different-first-page',
	'different-odd-and-even-pages',
	'next-page-section-break',
	'continuous-section-break',
	'even-page-section-break',
	'odd-page-section-break',
	'insert-table-of-contents',
	'update-table-of-contents',
	'insert-footnote',
	'insert-endnote',
	'paragraph-direction',
	'text-language',
	'custom-text-language-tag',
	'east-asian-language',
	'custom-east-asian-language-tag',
	'complex-script-language',
	'custom-complex-script-language-tag',
	'run-direction',
	'track-changes',
	'display-for-review',
	'previous-change',
	'next-change',
	'accept',
	'reject',
	'accept-all',
	'reject-all',
	'add-comment',
	'comments',
	'show-hidden-text',
	'page-thumbnails',
	'zoom',
	'layout-view',
	'print',
	'insert-row-above',
	'insert-row-below',
	'delete-row',
	'insert-column-left',
	'insert-column-right',
	'delete-column',
	'delete-table',
] as const;

export type RibbonActionId = (typeof RIBBON_ACTION_IDS)[number];

/** English control label of each action, the lookup key into the locale strings. Display-only. */
export const RIBBON_ACTION_LABELS: Readonly<Record<RibbonActionId, string>> = {
	paste: 'Paste',
	'insert-caption': 'Insert caption',
	'cross-reference': 'Cross-reference',
	ruler: 'Ruler',
	'page-setup-dialog': 'Page setup settings',
	'cover-page': 'Cover page',
	bookmark: 'Bookmark',
	sort: 'Sort',
	'find-options': 'Find options',
	'select-options': 'Select options',
	'add-text': 'Add text',
	'blank-page': 'Blank page',
	'read-aloud': 'Read aloud',
	gridlines: 'Gridlines',
	shading: 'Shading',
	borders: 'Borders',
	header: 'Header',
	footer: 'Footer',
	'page-number': 'Page number',
	'page-size': 'Page size',
	'font-dialog': 'Font settings',
	'paragraph-dialog': 'Paragraph settings',
	'indent-left': 'Indent left',
	'indent-right': 'Indent right',
	'zoom-actual-size': 'Zoom to 100%',
	'page-width': 'Page width',
	'one-page': 'One page',
	'word-count': 'Word count',
	spelling: 'Spelling',
	symbol: 'Symbol',
	'date-and-time': 'Date and time',
	'change-case': 'Change case',
	'format-painter': 'Format painter',
	'show-paragraph-marks': 'Show paragraph marks',
	'select-all': 'Select all',
	replace: 'Replace',
	cut: 'Cut',
	copy: 'Copy',
	'grow-font': 'Grow font',
	'shrink-font': 'Shrink font',
	'font-family': 'Font family',
	'font-size': 'Font size',
	bold: 'Bold',
	italic: 'Italic',
	underline: 'Underline',
	strikethrough: 'Strikethrough',
	superscript: 'Superscript',
	subscript: 'Subscript',
	'font-color': 'Font color',
	'text-highlight': 'Text highlight',
	'clear-formatting': 'Clear formatting',
	'decrease-indent': 'Decrease indent',
	'increase-indent': 'Increase indent',
	'spacing-after': 'Spacing after',
	'spacing-before': 'Spacing before',
	'line-spacing': 'Line spacing',
	'bulleted-list': 'Bulleted list',
	'numbered-list': 'Numbered list',
	'decrease-list-level': 'Decrease list level',
	'increase-list-level': 'Increase list level',
	'remove-list': 'Remove list',
	'align-left': 'Align left',
	'align-center': 'Align center',
	'align-right': 'Align right',
	justify: 'Justify',
	'find-and-replace': 'Find and replace',
	'insert-table': 'Insert table',
	'insert-picture': 'Insert picture',
	'format-picture': 'Format picture',
	'insert-link': 'Insert link',
	'insert-page-break': 'Insert page break',
	'insert-column-break': 'Insert column break',
	margins: 'Margins',
	orientation: 'Orientation',
	'vertical-alignment': 'Vertical alignment',
	columns: 'Columns',
	'page-number-format': 'Page number format',
	'page-numbering': 'Page numbering',
	'different-first-page': 'Different first page',
	'different-odd-and-even-pages': 'Different odd and even pages',
	'next-page-section-break': 'Next page section break',
	'continuous-section-break': 'Continuous section break',
	'even-page-section-break': 'Even page section break',
	'odd-page-section-break': 'Odd page section break',
	'insert-table-of-contents': 'Insert table of contents',
	'update-table-of-contents': 'Update table of contents',
	'insert-footnote': 'Insert footnote',
	'insert-endnote': 'Insert endnote',
	'paragraph-direction': 'Paragraph direction',
	'text-language': 'Text language',
	'custom-text-language-tag': 'Custom text language tag',
	'east-asian-language': 'East Asian language',
	'custom-east-asian-language-tag': 'Custom east asian language tag',
	'complex-script-language': 'Complex script language',
	'custom-complex-script-language-tag': 'Custom complex script language tag',
	'run-direction': 'Run direction',
	'track-changes': 'Track changes',
	'display-for-review': 'Display for review',
	'previous-change': 'Previous change',
	'next-change': 'Next change',
	accept: 'Accept',
	reject: 'Reject',
	'accept-all': 'Accept all',
	'reject-all': 'Reject all',
	'add-comment': 'Add comment',
	comments: 'Comments',
	'show-hidden-text': 'Show hidden text',
	'page-thumbnails': 'Page thumbnails',
	zoom: 'Zoom',
	'layout-view': 'Layout view',
	print: 'Print',
	'insert-row-above': 'Insert row above',
	'insert-row-below': 'Insert row below',
	'delete-row': 'Delete row',
	'insert-column-left': 'Insert column left',
	'insert-column-right': 'Insert column right',
	'delete-column': 'Delete column',
	'delete-table': 'Delete table',
};

export type { LegacyRibbonLabel };

/** A value `hiddenActions` accepts: a stable id, or (deprecated) the old English label. */
export type RibbonActionInput = RibbonActionId | LegacyRibbonLabel;

const labelToId = new Map<string, RibbonActionId>(
	RIBBON_ACTION_IDS.map((id) => [RIBBON_ACTION_LABELS[id], id]),
);

export function isRibbonActionId(value: string): value is RibbonActionId {
	return (RIBBON_ACTION_IDS as readonly string[]).includes(value);
}

/** The id of an English control label, or null. */
export function ribbonActionIdForLabel(label: string | null | undefined): RibbonActionId | null {
	return labelToId.get(label ?? '') ?? null;
}

/**
 * Maps `hiddenActions` input to ids. Deprecated English labels are converted and listed in
 * `legacy`; unknown values are dropped, matching how the ribbon ignored them before.
 */
export function normalizeRibbonActions(input: readonly string[]): {
	ids: RibbonActionId[];
	legacy: string[];
} {
	const ids: RibbonActionId[] = [];
	const legacy: string[] = [];
	for (const value of input) {
		if (isRibbonActionId(value)) ids.push(value);
		else {
			const id = labelToId.get(value);
			if (id) {
				ids.push(id);
				legacy.push(value);
			}
		}
	}
	return { ids, legacy };
}
