export {
	createDefaultRegistry,
	renderChartElement,
	renderChartSvgElement,
	renderConnectorElement,
	renderGroupElement,
	renderImageElement,
	renderInkElement,
	buildStrokeSvg,
	renderMediaElement,
	renderOleElement,
	renderPlaceholderElement,
	registerRichMediaRenderers,
	registerExtraRenderers,
	registerTableChartRenderers,
	renderSmartArtElement,
	renderSmartArtSvg,
	renderSmartArt3DElement,
	renderTableElement,
	collectThreeViews,
	withReusableThreeViews,
	renderTextBlock,
	renderTextShapeElement,
} from 'ooxml-ui/pptx/dom';
