// Compatibility exports: document operations live in ooxml-core.
export {
	YDOC_ASSETS_KEY,
	ASSET_ELEMENT_FIELDS,
	assetVersionKey,
	isAssetVersionKey,
	assetKey,
	getAssetsMap,
	isAssetRefKey,
	writeAssetFields,
	reconcileAssetFields,
	readAssetFields,
	isYTextLike,
	encodeTextBody,
	encodeSegmentsToDelta,
	decodeDelta,
	decodeTextBody,
	YDOC_SLIDES_KEY,
	YDOC_META_KEY,
	SCALAR_ELEMENT_KEYS,
	COMPLEX_ELEMENT_FIELDS,
	SCALAR_SLIDE_KEYS,
	COMPLEX_SLIDE_FIELDS,
	writeElementToYMap,
	readElementFromYMap,
	writeSlideToYMap,
	readSlideFromYMap,
	writeSlidesToYDoc,
	readSlidesFromYDoc,
	observeYDocSlides,
} from 'ooxml-core/pptx/editor/render/collaboration-sync';
export type {
	DeltaOp,
	YTextLike,
	YMapLike,
	YTransactionLike,
	YDeepObserver,
	YArrayLike,
	YDocLike,
	YjsFactories,
} from 'ooxml-core/pptx/editor/render/collaboration-sync';
