// Generates src/docx/generated/wml-simple-types.ts from the ECMA-376 Transitional XSDs in ../schemas.
// Run with `bun run gen:schema-types`; a Vitest drift check fails when the checked-in file is stale.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { DOMParser } from '@xmldom/xmldom';

const XSD_NS = 'http://www.w3.org/2001/XMLSchema';
const SCHEMA_DIR = new URL('../schemas/ecma-376-transitional/', import.meta.url);
export const OUTPUT_PATH = new URL('../src/docx/generated/wml-simple-types.ts', import.meta.url);

interface Source {
	file: string;
	/** Restrict generation to these simple types (all enumerations when omitted). */
	only?: readonly string[];
}
export const SOURCES: readonly Source[] = [
	{ file: 'wml.xsd' },
	{ file: 'shared-commonSimpleTypes.xsd' },
	{ file: 'dml-main.xsd', only: ['ST_SchemeColorVal'] },
	{ file: 'dml-wordprocessingDrawing.xsd', only: ['ST_RelFromH', 'ST_RelFromV'] },
];

interface EnumType {
	name: string;
	values: string[];
}

/** Top-level `xsd:simpleType`s that are string restrictions made of enumerations. */
function enumTypes(xml: string, only?: readonly string[]): EnumType[] {
	const document = new DOMParser().parseFromString(xml, 'application/xml');
	const types: EnumType[] = [];
	for (const node of Array.from(document.documentElement?.childNodes ?? [])) {
		const element = node as unknown as Element;
		if (element.nodeType !== 1 || element.localName !== 'simpleType') continue;
		const name = element.getAttribute('name');
		if (!name || (only && !only.includes(name))) continue;
		const restriction = Array.from(element.childNodes).find(
			(child) =>
				(child as Element).namespaceURI === XSD_NS && child.nodeName.endsWith('restriction'),
		) as Element | undefined;
		if (!restriction) continue;
		const values = Array.from(restriction.childNodes)
			.filter((child) => child.nodeType === 1 && (child as Element).localName === 'enumeration')
			.map((child) => (child as Element).getAttribute('value') ?? '');
		if (values.length) types.push({ name, values });
	}
	return types;
}

const typeName = (xsdName: string): string => xsdName.replace(/^ST_/, 'St').replace(/_/g, '');
const literal = (value: string): string => `'${value.replace(/[\\']/g, '\\$&')}'`;

/** Git may check schemas out as CRLF on Windows; provenance uses canonical UTF-8 LF text. */
export function schemaFingerprint(xml: string): string {
	return createHash('sha256').update(xml.replace(/\r\n/g, '\n')).digest('hex');
}

/** Builds the generated module text (deterministic; no timestamps). */
export function generate(): string {
	const provenance: string[] = [];
	const body: string[] = [];
	const seen = new Set<string>();
	for (const source of SOURCES) {
		const sourceText = readFileSync(new URL(source.file, SCHEMA_DIR), 'utf8').replace(
			/\r\n/g,
			'\n',
		);
		provenance.push(`//   ${source.file} sha256:${schemaFingerprint(sourceText)}`);
		for (const type of enumTypes(sourceText, source.only)) {
			if (seen.has(type.name)) throw new Error(`Duplicate simple type ${type.name}`);
			seen.add(type.name);
			const alias = typeName(type.name);
			body.push(
				`// ${source.file} ${type.name}`,
				'// prettier-ignore',
				`export const ${type.name} = [${type.values.map(literal).join(', ')}] as const;`,
				`export type ${alias} = (typeof ${type.name})[number];`,
				'// prettier-ignore',
				`export function is${alias}(value: unknown): value is ${alias} {`,
				`\treturn typeof value === 'string' && (${type.name} as readonly string[]).includes(value);`,
				'}',
				'',
			);
		}
	}
	return [
		'// GENERATED FILE - do not edit. Regenerate with `bun run gen:schema-types`.',
		'// Enumeration simple types from the ECMA-376 5th edition Transitional schemas',
		'// (schemas/ecma-376-transitional), generated by scripts/gen-schema-types.ts.',
		'// Sources (canonical UTF-8 LF text):',
		...provenance,
		'// This file is generated and exempt from the 300-line module guideline.',
		'',
		...body,
	].join('\n');
}

if (import.meta.main) {
	writeFileSync(OUTPUT_PATH, generate());
	console.log(`Wrote ${OUTPUT_PATH.pathname}`);
}
