"""Writes src/core/text/font-metrics/design-advances.generated.ts from the JSON that
scripts/record-visio-glyph-advances.ps1 records.

    python scripts/make-visio-advance-table.py <directory with glyph-advances.json>
"""
import io
import json
import os
import sys

source = os.path.join(sys.argv[1], 'glyph-advances.json')
tables = json.load(io.open(source, encoding='utf-8-sig'))
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
target = os.path.join(root, 'src', 'core', 'text', 'font-metrics', 'design-advances.generated.ts')

lines = [
    '/**',
    ' * Unhinted glyph advances per 1000 em for printable ASCII (code points 32 to 126, in order),',
    ' * regular and bold, as Visio 16 measures them: `TEXTWIDTH` of a repeated character at 100 pt',
    ' * (`scripts/record-visio-glyph-advances.ps1`). They equal the font files\' own advance widths',
    ' * (Calibri "P" is 1058/2048 em), so they suit any layout that does not hint or kern.',
    ' * GENERATED by `scripts/make-visio-advance-table.py`: do not edit by hand.',
    ' */',
    'export const DESIGN_ADVANCES: Readonly<',
    '\tRecord<string, { readonly regular: string; readonly bold: string }>',
    '> = {',
]
fonts = {}
for table in tables.values():
    row = ' '.join(
        ('%g' % round(table['advances'][str(code)], 2)) for code in range(32, 127)
    )
    fonts.setdefault(table['font'], {})['bold' if table['bold'] else 'regular'] = row
for font in sorted(fonts):
    lines.append('\t%s: {' % json.dumps(font.lower()).replace('"', "'"))
    lines.append("\t\tregular:\n\t\t\t'%s'," % fonts[font]['regular'])
    lines.append("\t\tbold:\n\t\t\t'%s'," % fonts[font]['bold'])
    lines.append('\t},')
lines.append('};')
io.open(target, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('wrote', target)
