/** Format-neutral, DOM-free chart data algorithms shared by Office formats. */
export * from './regression';
export * from './box-stats';
export * from './blank-display';
export * from './stacked-series';
export * from './axis-nice';
export * from './histogram-binning';
export * from './treemap-squarify';
export * from './trendline-equation';
export * from './radar-geometry';
export * from './pie-best-fit';
export * from './pie-label-collision';
export * from './color-palettes';
export * from './color-style';
export * from './style-definition';
export * from './read-style';
export * from './read-formatting';
export * from './gradient-definition';
export * from './bar-cluster-geometry';
