/** Format-neutral, DOM-free chart data algorithms shared by Office formats. */
export * from './regression';
export * from './box-stats';
export * from './blank-display';
export * from './stacked-series';
export * from './axis-nice';
export * from './histogram-binning';
export * from './treemap-squarify';
export * from './trendline-equation';
export * from './radar-geometry';
export * from './pie-best-fit';
export * from './pie-label-collision';
export * from './color-palettes';
export * from './color-style';
export * from './style-definition';
export * from './built-in-text-style';
export * from './read-style';
export * from './read-formatting';
export * from './write-axis-formatting';
export * from './write-fill-formatting';
export * from './gradient-definition';
export * from './gradient-markup';
export * from './gradient-stop-edit';
export * from './bar-cluster-geometry';
export * from './manual-layout';
export * from './write-layout-formatting';
export * from './model';
export * from './data-cache';
export { parseChartSpace } from './parse-space';
export { writeChartSpace, type WriteChartSpaceOptions } from './write-space';
export { CHART_GROUP_ELEMENTS } from './parse-plot';
export * from './render/index';
