/**
 * The English control labels `hiddenActions` accepted before ids existed. Deprecated: accepted for
 * one more release, mapped to ids, and reported through a `document-warning` event.
 */
export type LegacyRibbonLabel =
	| 'Font family'
	| 'Font size'
	| 'Bold'
	| 'Italic'
	| 'Underline'
	| 'Strikethrough'
	| 'Superscript'
	| 'Subscript'
	| 'Font color'
	| 'Text highlight'
	| 'Clear formatting'
	| 'Decrease indent'
	| 'Increase indent'
	| 'Spacing after'
	| 'Spacing before'
	| 'Line spacing'
	| 'Bulleted list'
	| 'Numbered list'
	| 'Decrease list level'
	| 'Increase list level'
	| 'Remove list'
	| 'Align left'
	| 'Align center'
	| 'Align right'
	| 'Justify'
	| 'Find and replace'
	| 'Insert table'
	| 'Insert picture'
	| 'Format picture'
	| 'Insert link'
	| 'Insert page break'
	| 'Insert column break'
	| 'Margins'
	| 'Orientation'
	| 'Vertical alignment'
	| 'Columns'
	| 'Page number format'
	| 'Page numbering'
	| 'Different first page'
	| 'Different odd and even pages'
	| 'Next page section break'
	| 'Continuous section break'
	| 'Even page section break'
	| 'Odd page section break'
	| 'Insert table of contents'
	| 'Update table of contents'
	| 'Update fields'
	| 'Insert table of figures'
	| 'Insert footnote'
	| 'Insert endnote'
	| 'Paragraph direction'
	| 'Text language'
	| 'Custom text language tag'
	| 'East Asian language'
	| 'Custom east asian language tag'
	| 'Complex script language'
	| 'Custom complex script language tag'
	| 'Run direction'
	| 'Track changes'
	| 'Display for review'
	| 'Previous change'
	| 'Next change'
	| 'Accept'
	| 'Reject'
	| 'Accept all'
	| 'Reject all'
	| 'Add comment'
	| 'Comments'
	| 'Show hidden text'
	| 'Page thumbnails'
	| 'Zoom'
	| 'Layout view'
	| 'Print'
	| 'Insert row above'
	| 'Insert row below'
	| 'Delete row'
	| 'Insert column left'
	| 'Insert column right'
	| 'Delete column'
	| 'Delete table';
